config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get   "/:user_id/dashboard",                  to: "pages#dashboard",                as: :dashboard
  get   "reservations/toggle_confirmation",     to: "reservations#toggle_confirmation"
  get   "reservations/rent_out",                to: "reservations#rent_out"
  get   "reservations/rent_in",                 to: "reservations#rent_in"
  get   "reservations/rent_reset",              to: "reservations#rent_reset"

  resources :books do
    resources :reviews, only:[:create, :update, :new, :edit]
    resources :wishlists, only:[:create]
    resources :book_ownerships, only:[:new]
  end

  resources :reviews, only:[:destroy]

  resources :book_ownerships do
    resources :reservations, only: [ :create, :destroy, :update]
  end

  resources :wishlists, only: [:index, :destroy]

  resources :reservations, only: [:index, :update]

  resources :adhesions, only: [:create, :destroy]

  resources :families, only: [:index, :create, :destroy, :update]
end

app/views/pages/_reservation.html.erb
<div class="card-product">
  <img src="<%= cl_image_path request.book_ownership.book.cover.key %>" alt="" class="reservation-book-img">
  <div class="card-product-infos d-flex justify-content-between align-items-center flex-grow-1">
    <div class="flex-grow-1 ">
      <h6 class="pr-5"><%= request.book_ownership.book.title %></h6>
      <% if request.confirmed? %>
        <i class="fas fa-check-circle font-awesome pb-1 accepted"></i>
      <% end %>
        <% if (request.confirmed? && request.rented?) %>
          <p>Asked by <strong> <%= request.user.full_name %></strong></p>
          <p>From <strong><%= request.start_date.strftime('%d/%m/%Y') %></strong> until: <strong><%= request.end_date.strftime('%d/%m/%Y') %></strong></p>
          <p>Out since <strong><%= request.rentedout.strftime('%d/%m/%Y') %></strong></p>
        <% elsif (request.confirmed? && !request.rented) %>
              <% if !request.rentedout.nil? && !request.rentedin.nil?  %>
                <p>Asked by <strong> <%= request.user.full_name %></strong></p>
                <p>From <strong><%= request.start_date.strftime('%d/%m/%Y') %></strong> until: <strong><%= request.end_date.strftime('%d/%m/%Y') %></strong></p>
                <p>Out from <strong><%= request.rentedout.strftime('%d/%m/%Y') %></strong> until: <strong><%= request.rentedin.strftime('%d/%m/%Y') %></strong></p>
              <% else %>
                <p>Asked by <strong> <%= request.user.full_name %></strong></p>
                <p>From <strong><%= request.start_date.strftime('%d/%m/%Y') %></strong> until: <strong><%= request.end_date.strftime('%d/%m/%Y') %></strong></p>
                <p>"<%= request.message %>"</p>
              <% end %>
        <% else %>
          <p>Asked by <strong> <%= request.user.full_name %></strong></p>
          <p>From <strong><%= request.start_date.strftime('%d/%m/%Y') %></strong> until: <strong><%= request.end_date.strftime('%d/%m/%Y') %></strong></p>
          <p>"<%= request.message %>"</p>
        <% end %>
    </div>
    <div class="reservation-actions">
      <% if (request.confirmed? && request.rented?) %>
          <%= link_to "<i class=\"fas fa-sign-in-alt\"></i>".html_safe, reservations_rent_in_path(request), class:"m-2 font-awesome" %>
      <% elsif (request.confirmed? && !request.rented) %>
          <%= link_to "<i class=\"fas fa-sign-out-alt\"></i>".html_safe, reservations_rent_out_path(request), class:"m-2 font-awesome" %>
          <%= link_to "<i class=\"far fa-times-circle\"></i>".html_safe, reservations_toggle_confirmation_path(request), class:"m-2 font-awesome" %>
      <% else %>
        <%= link_to "<i class=\"fas fa-check\"></i>".html_safe, reservations_toggle_confirmation_path(request), class: "m-2 font-awesome" %>
        <%= link_to "<i class=\"far fa-trash-alt\"></i>".html_safe, book_ownership_reservation_path(request.book_ownership, request), method: :delete, data: { confirm: "Are you sure?" }, class: "m-2 font-awesome" %>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<% if @user == current_user %>
  <h1 class="mt-2 p-0">My Dashboard</h1>
<% else %>
  <h1><%= @user.full_name %></h1>
<% end %>

<div class="dashboard-card" id="family">

  <div class="d-flex justify-content-between align-items-center">
    <h2>Families</h2>
    <%= link_to "#", "data-toggle"=>"modal",  "data-target"=>"#CreateFamily", class:"btn-add" do %>
      <i class="fas fa-plus"></i>
    <% end %>
  </div>
  <div class="dashboard-grid">
    <% @families.each do |family| %>
      <div class="family-card">
        <div class="img-header" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.5)), url(<%= cl_image_path family.picture.key %>)">
          <h4><%= family.name %></h4>
        </div>
        <div class="members">
          <% family.users.includes(avatar_attachment: :blob).each do |member| %>
            <div class="member">
              <%= cl_image_tag member.avatar.key, class: "avatar-small" %>
              <p><%= member.full_name%></p>
              <p><%= member.book_ownerships.count %> books</p>
            </div>
          <% end %>
        </div>
          <% if family.familyadmin_id == current_user.id %>
            <%= link_to "Add a member!", "#", "data-toggle"=>"modal",  "data-target"=>"#AddMember#{family.id}", class:"btn-booker add-member" %>
          <% end %>
        <div class="family-action">
          <% if family.familyadmin_id == current_user.id %>
            <%= link_to "<i class=\"far fa-edit\"></i>".html_safe, "#", "data-toggle"=>"modal",  "data-target"=>"#EditFamily#{family.id}", class:"m-2 font-awesome" %>
            <%= link_to "<i class=\"far fa-trash-alt\"></i>".html_safe, family_path(family), method: :delete, data: { confirm: "Are you sure?" }, class: "m-2 font-awesome" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="col-12 col-lg-6">
    <div class="dashboard-card">
      <h2>My reservations</h2>

      <% @my_reservations.each do |reservation| %>
        <div class="card-product">
          <img src="<%= cl_image_path reservation.book_ownership.book.cover.key %>" alt="" class="reservation-book-img">
          <div class="card-product-infos">
            <h6 class="pr-5"><%= reservation.book_ownership.book.title %></h6>
            <% if reservation.confirmed? %>
              <i class="fas fa-check-circle font-awesome pb-1 accepted"></i>
            <% end %>
            <p>Asked to <strong><%= reservation.book_ownership.user.full_name %></strong></p>
            <p>From
                <strong><%= reservation.start_date.strftime('%d/%m/%Y') %></strong>
                until the
                <strong><%= reservation.end_date.strftime('%d/%m/%Y') %></strong></p>
            <p>"<%= reservation.message %>"</p>
            <div class="reservation-actions">
              <%= link_to "<i class=\"far fa-edit\"></i>".html_safe, "#", "data-toggle"=>"modal",  "data-target"=>"#EditReservationModal#{reservation.id}", class:"m-2 font-awesome" %>
              <%= link_to "<i class=\"far fa-trash-alt\"></i>".html_safe, book_ownership_reservation_path(reservation.book_ownership, reservation), method: :delete, data: { confirm: "Are you sure?" }, class: "m-2 font-awesome" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-lg-6">
    <div class="dashboard-card">
      <h2>Shelve requests</h2>
      <% @my_requests.each do |request| %>
        <%= render 'reservation', request: request %>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-lg-6">
    <div class="dashboard-card">
      <h2>Books I loaned</h2>
      <% @my_rented.each do |request| %>
        <%= render 'reservation', request: request %>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-lg-6">
    <div class="dashboard-card">
      <h2>Bookings history</h2>
      <% @my_previously_rented.each do |request| %>
        <%= render 'reservation', request: request %>
      <% end %>
    </div>
  </div>
  <div class="col-12 col-lg-6">
    <div class="dashboard-card">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Shelve</h2>
        <%= link_to new_book_path, class: "btn-add" do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
      <div class="dashboard-grid">
        <% @books.each do |book| %>

          <%= link_to book_path(book) do %>
            <div class="card-category small text-center dashboard"  style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= cl_image_path book.cover.key %>)">
              <div class="content p-2 py-4 d-flex justify-content-between flex-column h-80">
                <h5 class="book-info"><%= book.title %></h5>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-12 col-lg-6">
    <div class="dashboard-card">
      <div class="d-flex justify-content-between align-items-center">
        <h2>Wishlist</h2>
        <%= link_to new_book_path, class: "btn-add" do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
      <div class="dashboard-grid">
        <% @wishlist.each do |book| %>

          <%= link_to book_path(book) do %>
            <div class="card-category small text-center"  style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= cl_image_path book.cover.key %>)">
              <div class="content p-2 py-4 d-flex justify-content-between flex-column h-80">
                <h5 class="book-info"><%= book.title %></h5>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= render 'shared/family' %>

app/views/pages/home.html.erb
<div class="banner">
  <div class="container">
    <%= image_tag("logo1.png", class: "logo") %>
    <br>
    <h1 class="mt-0.5"><strong>Spend Less, Read More</strong></h1>
    <br>
    <br>
    <br>
    <% if current_user %>
      <%= link_to "", dashboard_path(current_user), class: "far fa-arrow-alt-circle-down", id: "go" %>
    <% else %>
      <%= link_to "", books_path, class: "far fa-arrow-alt-circle-down", id: "go"%>
    <% end %>
  </div>
</div>