config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get   "/:user_id/dashboard",                  to: "pages#dashboard",                as: :dashboard
  get   "reservations/toggle_confirmation",     to: "reservations#toggle_confirmation"
  get   "reservations/rent_out",                to: "reservations#rent_out"
  get   "reservations/rent_in",                 to: "reservations#rent_in"
  get   "reservations/rent_reset",              to: "reservations#rent_reset"

  resources :books do
    resources :reviews, only:[:create, :update, :new, :edit]
    resources :wishlists, only:[:create]
    resources :book_ownerships, only:[:new]
  end

  resources :reviews, only:[:destroy]

  resources :book_ownerships do
    resources :reservations, only: [ :create, :destroy, :update]
  end

  resources :wishlists, only: [:index, :destroy]

  resources :reservations, only: [:index, :update]

  resources :adhesions, only: [:create, :destroy]

  resources :families, only: [:index, :create, :destroy, :update]
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :cover
  belongs_to :category
  has_many :wishlists, dependent: :destroy
  has_many :book_ownerships, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :users, through: :book_ownerships
  after_save :upload_default_cover
  validates :ISBN, uniqueness: true, :allow_blank => true
  validates :title, presence: true
  validates :author, presence: true

  $categories = Category.select('distinct name').collect { |p| p.name }

  include PgSearch::Model
  pg_search_scope :global_search,
    against: [[:title, 'A'], :description, [:author, 'B'], :year, :ISBN],
    associated_against: {
      category: :name,
      users: [:first_name, :last_name, :email, :username]
    },
    using: {
      tsearch: { prefix: true }
    }

  private

  def upload_default_cover
    file = File.open("#{Rails.root}/app/assets/images/defaultcover.jpg")
    cover.attach(io: file, filename: 'cover.jpg', content_type: 'image/jpg') unless cover.attached?
  end
end

app/controllers/books_controller.rb
require 'json'
require 'rest-client'
require 'open-uri'

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  def index
    @book = Book.new
    @user_families = current_user.families
    @no_result = false
    if params[:search].present?
      do_global_search
    else
      my_books
    end
  end

  def show
    @reservation = Reservation.new
    @review = Review.new
    @book_ownerships = @book.book_ownerships
    if Review.where(book_id: @book.id).empty?
      @avg_rating = "No ratings yet"
    else
      book_reviews_rating = Review.where(book_id: @book.id).map(&:rating)
      @avg_rating = (book_reviews_rating.sum(0.0) / book_reviews_rating.size).round(2)
    end
    @wishlist = Wishlist.where(user_id: current_user, book_id: @book.id)
  end

  def new
    @book = Book.new
  end

  def create
    #  Lisbn.new(params[:book][:ISBN]).valid? will return true if a valid ISBN is supplied. should be implemented
    if params[:book][:title].nil?
      isbn_params = parse_by_isbn(params[:book][:ISBN], params)
      if isbn_params.is_a? String
        @book = Book.new
        render :new
      end
      if Book.find_by(ISBN: isbn_params[:parameters][:ISBN]).nil?
        file = URI.open(isbn_params[:file])
        @book = Book.new(isbn_params[:parameters])
        @book.cover.attach(io: file, filename: 'cover.png', content_type: 'image/png')
      else
        @book = Book.find_by ISBN: isbn_params[:parameters][:ISBN]
      end
    else
      @book = Book.new(book_params)
      @book.category = Category.find(params[:book][:category_id])
    end
    if @book.save
      if params[:book][:wishlist] == "1"
        Wishlist.create(book: @book, user: current_user)
      else
        BookOwnership.create(book: @book, user: current_user)
      end
      redirect_to book_path(@book)
    else
      render :new
    end
  end

  def destroy
    book_ownership = BookOwnership.find_by(book_id: @book.id, user_id: current_user.id)
    book_ownership.destroy
    redirect_to books_path
  end

  def update
    @book.update(book_params)
    redirect_to book_path(@book)
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :year, :category_id, :description, :user, :cover, :ISBN)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def parse_by_isbn(isbn, params)
    response = RestClient.get "https://www.googleapis.com/books/v1/volumes?q=isbn%3D#{isbn}&key=#{ENV['GOOGLEKEY']}"
    i = 0
    10.times do
      i += 1
      file = JSON.parse(response)
      break if file["totalItems"].positive?
    end
    return "No book found. Please enter it manually" if i >= 10

    json = JSON.parse(response)["items"][0]["volumeInfo"]
    params[:book][:title] = json["title"]
    params[:book][:author] = json["authors"][0]
    params[:book][:year] = json["publishedDate"]
    params[:book][:description] = json["description"]
    params[:book][:ISBN] = isbn
    json["imageLinks"].nil? ? params[:book][:image_url] = "https://images.isbndb.com/covers/02/21/#{isbn}.jpg" : params[:book][:image_url] = json["imageLinks"]["thumbnail"]
    { parameters: params.require(:book).permit(:title, :author, :year, :description, :ISBN, :category_id), file: params[:book][:image_url] }
  end

  def do_global_search
    @books = Book.all
    @books = Book.includes(:category, cover_attachment: :blob).global_search(params[:search][:term]) if params[:search][:term].present?
    @books = @books.where(category_id: params[:search][:category]) if params[:search][:category].present?
    @books = current_user.families.select{|fam| fam.id == params[:search][:families].to_i }.flat_map(&:books).uniq & @books if params[:search][:families].present?
    pp "------------------"
    @books = BookOwnership.where(user_id: params[:search][:user]).map(&:book) if params[:search][:user].present?
    pp params
    pp @books
    pp "------------------"
    @no_result = true if @books.size.zero?
    @books = my_books if @books.size.zero?
  end

  def my_books
    @books = []
    @user_families.each do |family|
      @books << family.users.includes(books: [:category, cover_attachment: :blob]).flat_map(&:books)
      @books = @books.flatten.uniq
    end
    @books
  end
end

app/views/books/_book.html.erb
<% books.each do |book| %>
  <%= link_to book_path(book) do %>
    <div class="card-category text-center <%= "mybookhighlight" if book.users.include?(current_user) %>"  style="background-image: linear-gradient(rgba(0,0,0,0), rgba(0,0,0,0)), url(<%= cl_image_path book.cover.key %>)">
      <div class="content py-4 d-flex justify-content-between flex-column">
        <h3 class="book-info"><%= book.title %></h3>
        <h5 class="book-info">by <%= book.author %></h5>
        <h5 class="book-info"><%= book.category.name %></h5>
      </div>
    </div>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<%= simple_form_for book do |f| %>
  <%= f.input :title %>
  <div class="row">
    <div class="col-9">
      <%= f.input :author %>
    </div>
    <div class="col-3">
      <%= f.input :year %>
    </div>
  </div>

  <%= f.association :category, input_html: { style: 'width: 466px', class: 'select2 form-control' } %>
  <div class="row">
    <div class="col-6">
      <%= f.input :cover, as: :file%>
    </div>
    <div class="col-6">
      <%= f.input :ISBN %>
    </div>
  </div>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn-booker" %>
<% end %>

app/views/books/_search.html.erb
<h3 class="text-center">Quick Access</h3>
  <div class="book-search">
    <form id="searchbar" class="" action="/books" accept-charset="UTF-8" method="get">
      <input class="form-control" name="search[term]" placeholder="Search">
    </form>
    <%= simple_form_for :search, url: books_path, method: "get" do |f| %>
      <%= f.input :category, required: false, collection: Category.find(current_user.families.flat_map(&:books).map(&:category_id)), prompt: "Category", label: false, input_html: { class: 'select2 w-100' } %>
      <%= f.input :families, required: false, collection: current_user.families, prompt: "Family", label: false, input_html: { class: 'select2 w-100' } %>
      <%= f.input :user, required: false, collection: User.find(current_user.families.flat_map(&:users).map(&:id)), label_method: :full_name, prompt: "Users", label: false, input_html: { class: 'select2 w-100' } %>
      <%= f.button :submit, "Filter", class: "btn-booker w-100"%>
    <% end %>
  </div>

app/views/books/index.html.erb
<div class="index-banner">
  <h1 id="index-title">Let's <i class="fas fa-search" style="color:$blue; font-size: 1.2em"></i> in your friends libraries!</h1>
</div>
<div id ="index-container">
  <div class="row">
    <div class="col-12 col-md-9" id="book-row">
      <% if @no_result == true %>
        <div class="p-3 mb-2 bg-warning text-dark"><strong>Hey you</strong> Your search gave no result!
        </div>
      <% end %>
      <% if @books.empty? %>
        <h2>You currently have no books in your library!</h2>
      <% else %>
        <div class="cards">
          <%= render 'book', books: @books %>
        </div>
      <% end %>
    </div>
    <div class="col-12 col-md-3 ">
      <%= render 'search' %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="index-banner">
  <h1 id="index-title">Let's add a new book!</h1>
</div>
<div class="container">
  <div class="row py-3">
    <div class="col-12 col-md-8 px-5 br-2">
      <h2>Manual input</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class="col-12 col-md-3">
      <h2>Fast ISBN input</h2>
      <%= simple_form_for @book, namespace: 'isbn_book' do |f| %>
        <%= f.input :ISBN , label: "Look at the back of your book you will find a 10 digits number"%>
        <%= f.association :category, input_html: { class: 'select2' } %>
        <%= f.input :wishlist, :as => :boolean, input_html: {checked: false} %>
        <%= f.button :submit, class: "btn-booker" %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <% if @book.reviews.empty? {size = "col-lg-12"}%>
      <% else size = "col-lg-9"%>
    <% end %>
    <div class="col-12 <%= size %> ">
      <div class="title-add d-flex justify-content-between align-items-start py-3">
        <h1 class="pr-3"><%= @book.title %> <span class="year">(<%= @book.year %>)</span></h1>
        <% unless @book.users.include?(current_user) || @book.users.empty? %>
          <li type="button" class="btn-booker" data-toggle="modal" data-target="#ReservationModal"> Book it</li>
        <% else %>
          <li type="button" class="btn-booker" data-toggle="modal" data-target="#ReservationModal">Block it</li>
        <% end %>
     </div>
      <div class="picture-and-info d-flex justify-content-between">
        <img src="<%= cl_image_path @book.cover.key %>" alt="" class="covers-show" class>
        <div class="info px-4">
          <h2>by <%= @book.author %></h2>
          <div class="book-description">
            <p><%= @book.description %></p>
          </div>
          <div class="owners-avatar d-flex align-items-center">
            <p class ="mr-3">Owners:</p>
            <div class="d-inline-block mb-3">
              <% @book.users.each do |member| %>
                <% member.avatar.attached? == true ? tag = member.avatar.key : tag = 'defaultavatar' %>
                <%= cl_image_tag tag, class: "avatar-small" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="book-actions d-flex justify-content-around">
        <% if @wishlist&.empty? || @wishlist.nil? %>
          <%= link_to "Wishlist", book_wishlists_path(@book), method: :post%>
        <% else %>
          <%= link_to "Remove from wishlist", wishlist_path(@wishlist[0]), method: :delete%>
        <% end %>
        <% if (@book.users.include?(current_user)  || current_user.siteadmin?) %>
          <%= link_to "Edit Book", "#", "data-toggle"=>"modal",  "data-target"=>"#EditModal" %>
          <%= link_to "Remove Book", book_path(@book), method: :delete %>
        <% end %>
        <% unless @book.users.include?(current_user)%>
          <%= link_to "Add to my shelve", new_book_book_ownership_path(@book) %>
        <% end %>
      </div>
      <br>
      <h3>You read this book? Give a review! </h3>
      <%= render "reviews/form", book: @book, review: @review %>
    </div>

    <div class="col-12 col-lg-3 reviews">
      <% unless @book.reviews.empty?%>
        <h3 class = "py-3 pr-3">Reviews <em class="avg-rating"><%= @avg_rating %>/5</em></h3>
        <% @book.reviews.each do |review| %>
        <div class="review">
          <div class="avatar-rating d-flex justify-content-between align-items-center">
            <% tag = review.user.avatar.key if review.user.avatar.attached? == true %>
            <%= cl_image_tag tag, class: "avatar"%>
                <% review.rating.times do %>
                  <%= "<i style=\"color: #706897 \" class=\"fas fa-star\"></i>".html_safe %>
                <% end %>
                <% (5 - review.rating).times do %>
                  <%= "<i style=\"color: #706897 \" class=\"far fa-star\"></i>".html_safe %>
                <% end %>
              by <strong><%= review.user.first_name %></strong></p>
          </div>
          <div class="d-flex justify-content-between">
          <p class="flex-grow-1 text-justify"><%= review.content %></p>
            <% if (review.user == current_user || current_user.siteadmin?) %>
              <p class="text-center">
                <%= link_to "<i class=\"far fa-trash-alt\"></i>".html_safe, review_path(review), method: :delete, data: { confirm: "Are you sure?" }, class: "m-2 font-awesome" %>
                <%= link_to "<i class=\"far fa-edit\"></i>".html_safe, "#", "data-toggle"=>"modal",  "data-target"=>"#EditReviewModal#{review.id}", class:"m-2 font-awesome " %>
              </p>
            <% end %>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>

  <!-- Edit Modal -->
  <% if (@book.users.include?(current_user) || current_user.siteadmin?) %>
    <div class="modal fade" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="EditModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="EditModalLongTitle">Edit this Book!</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <%= render 'form', book: @book %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!-- Reservation Modal -->
  <% unless @book.users.empty? %>
    <div class="modal fade" id="ReservationModal" tabindex="-1" role="dialog" aria-labelledby="ReservationModalTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="ReservationModalLongTitle">Reservations</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <label>Choose who you want to rent to:
              <select class="name" name="name">
                <option value="">Select One …</option>
                <% @book_ownerships.each do |bo| %>
                <option value="user-<%= bo.user_id %>"><%= bo.user.full_name %></option>
                <% end %>
              </select>
            </label>
            <% @book_ownerships.each do |bo| %>
              <div id='user-<%= bo.user_id %>' class="hidden form-reservation-container">
                  <%= render "reservations/form", book_ownership: bo, reservation: @reservation %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <!-- Edit Review Modal -->
  <% @book.reviews.select{|review| review.user == current_user}.each do |review| %>
    <% if (review.user == current_user || current_user.siteadmin?) %>
      <div class="modal fade" id="EditReviewModal<%= review.id %>" tabindex="-1" role="dialog" aria-labelledby="EditReviewModalTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="EditModalLongTitle">Edit this Book!</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            <div class="modal-body">
              <%= render "reviews/form", book: @book, review: review %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>